version: '3.8'

services:
  backend:
    image: muratali/kitaphub-backend:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == backend-node
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/kitaphub
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    deploy:
      placement:
        constraints:
          - node.hostname == backend-node
    environment:
      POSTGRES_DB: kitaphub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pg-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    deploy:
      placement:
        constraints:
          - node.hostname == frontend-node
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-keycloak
      KC_DB_URL_DATABASE: pdb
    ports:
      - "9091:8080"

  postgres-keycloak:
    image: postgres:16
    deploy:
      placement:
        constraints:
          - node.hostname == frontend-node
    environment:
      POSTGRES_DB: pdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

volumes:
  pg-data: