name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" \
            | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t muratali/kitaphub-backend:latest .
          docker push muratali/kitaphub-backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Trigger ECS Deployment
        run: |
          aws ecs update-service \
            --cluster kitaphubCluster \
            --service kitaphub-backend-task-service-w4mubxls \
            --force-new-deployment

  dast:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Start your app container
        run: |
          docker run -d -p 8080:8080 --name kitaphub muratali/kitaphub-backend:latest
          # Wait for app to be ready (no authentication needed)
          docker run --network container:kitaphub curlimages/curl \
            --retry 12 --retry-delay 5 \
            --connect-timeout 5 --max-time 10 \
            http://localhost:8080/hello || true
          sleep 3

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'http://localhost:8080/hello'
          cmd_options: '-r report_html.html -j report.json'
          # No authentication parameters needed

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-${{ github.run_number }}
          path: |
            report_html.html
            report.json
          retention-days: 3
